GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/64128132240af24057e89926

###

DELETE http://localhost:3001/api/persons/641365e73b5544bd2cf05166

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "sei lá",
    "phone": "1234"
}

###

PUT http://localhost:3001/api/persons/6413697ce526111f0e063e09
Content-Type: application/json

{
    "name": "joão",
    "phone": "1234"
}